name: Linting

on:
  workflow_dispatch:
  pull_request:
    branches:
      - master
    paths:
      - "src/**"
  push:
    branches:
      - master
    paths:
      - "src/**"

jobs:
  quartz:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code.
        uses: actions/checkout@main

      - name: Tests
        run: true
